# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: influence_service_copy.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cinfluence_service_copy.proto\x12\x16influence_service_copy\"\xcd\x01\n\x10InfluenceRequest\x12\x12\n\ntrain_data\x18\x01 \x01(\x0c\x12\r\n\x05model\x18\x02 \x01(\x0c\x12\x11\n\ttest_data\x18\x03 \x01(\x0c\x12\x14\n\x0ctrain_labels\x18\x04 \x01(\x0c\x12\x13\n\x0btest_labels\x18\x05 \x01(\x0c\x12\x17\n\x0fnum_influential\x18\x06 \x01(\x05\x12\x1b\n\x13untransformed_train\x18\x07 \x01(\x0c\x12\"\n\x1auntransformed_train_labels\x18\x08 \x01(\x0c\"K\n\x11InfluenceResponse\x12\x12\n\ninfluences\x18\x01 \x03(\x02\x12\x10\n\x08positive\x18\x02 \x01(\x0c\x12\x10\n\x08negative\x18\x03 \x01(\x0c\"/\n\nPDPRequest\x12\x12\n\nparam_grid\x18\x01 \x01(\t\x12\r\n\x05model\x18\x02 \x01(\x0c\"4\n\x0bPDPResponse\x12\x11\n\thp_values\x18\x01 \x01(\t\x12\x12\n\npdp_values\x18\x02 \x01(\t\"U\n\x0cPDP2DRequest\x12\x12\n\nparam_grid\x18\x01 \x01(\t\x12\r\n\x05model\x18\x02 \x01(\x0c\x12\x10\n\x08\x66\x65\x61ture1\x18\x03 \x01(\t\x12\x10\n\x08\x66\x65\x61ture2\x18\x04 \x01(\t\"3\n\rPDP2DResponse\x12\n\n\x02xi\x18\x01 \x01(\t\x12\n\n\x02yi\x18\x02 \x01(\t\x12\n\n\x02zi\x18\x03 \x01(\t\"=\n\nALERequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x12\n\nparam_grid\x18\x02 \x01(\t\x12\r\n\x05model\x18\x03 \x01(\x0c\"\x1b\n\x0b\x41LEResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t2\x8d\x03\n\x14InfluenceServiceCopy\x12j\n\x11\x43omputeInfluences\x12(.influence_service_copy.InfluenceRequest\x1a).influence_service_copy.InfluenceResponse(\x01\x12U\n\nComputePDP\x12\".influence_service_copy.PDPRequest\x1a#.influence_service_copy.PDPResponse\x12[\n\x0c\x43omputePDP2D\x12$.influence_service_copy.PDP2DRequest\x1a%.influence_service_copy.PDP2DResponse\x12U\n\nComputeALE\x12\".influence_service_copy.ALERequest\x1a#.influence_service_copy.ALEResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'influence_service_copy_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_INFLUENCEREQUEST']._serialized_start=57
  _globals['_INFLUENCEREQUEST']._serialized_end=262
  _globals['_INFLUENCERESPONSE']._serialized_start=264
  _globals['_INFLUENCERESPONSE']._serialized_end=339
  _globals['_PDPREQUEST']._serialized_start=341
  _globals['_PDPREQUEST']._serialized_end=388
  _globals['_PDPRESPONSE']._serialized_start=390
  _globals['_PDPRESPONSE']._serialized_end=442
  _globals['_PDP2DREQUEST']._serialized_start=444
  _globals['_PDP2DREQUEST']._serialized_end=529
  _globals['_PDP2DRESPONSE']._serialized_start=531
  _globals['_PDP2DRESPONSE']._serialized_end=582
  _globals['_ALEREQUEST']._serialized_start=584
  _globals['_ALEREQUEST']._serialized_end=645
  _globals['_ALERESPONSE']._serialized_start=647
  _globals['_ALERESPONSE']._serialized_end=674
  _globals['_INFLUENCESERVICECOPY']._serialized_start=677
  _globals['_INFLUENCESERVICECOPY']._serialized_end=1074
# @@protoc_insertion_point(module_scope)
