# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: influence_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17influence_service.proto\x12\x11influence_service\"\xcd\x01\n\x10InfluenceRequest\x12\x12\n\ntrain_data\x18\x01 \x01(\x0c\x12\r\n\x05model\x18\x02 \x01(\x0c\x12\x11\n\ttest_data\x18\x03 \x01(\x0c\x12\x14\n\x0ctrain_labels\x18\x04 \x01(\x0c\x12\x13\n\x0btest_labels\x18\x05 \x01(\x0c\x12\x17\n\x0fnum_influential\x18\x06 \x01(\x05\x12\x1b\n\x13untransformed_train\x18\x07 \x01(\x0c\x12\"\n\x1auntransformed_train_labels\x18\x08 \x01(\x0c\"K\n\x11InfluenceResponse\x12\x12\n\ninfluences\x18\x01 \x03(\x02\x12\x10\n\x08positive\x18\x02 \x01(\x0c\x12\x10\n\x08negative\x18\x03 \x01(\x0c\x32t\n\x10InfluenceService\x12`\n\x11\x43omputeInfluences\x12#.influence_service.InfluenceRequest\x1a$.influence_service.InfluenceResponse(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'influence_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_INFLUENCEREQUEST']._serialized_start=47
  _globals['_INFLUENCEREQUEST']._serialized_end=252
  _globals['_INFLUENCERESPONSE']._serialized_start=254
  _globals['_INFLUENCERESPONSE']._serialized_end=329
  _globals['_INFLUENCESERVICE']._serialized_start=331
  _globals['_INFLUENCESERVICE']._serialized_end=447
# @@protoc_insertion_point(module_scope)
