# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xai_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11xai_service.proto\"v\n\x13\x45xplanationsRequest\x12\x18\n\x10\x65xplanation_type\x18\x01 \x01(\t\x12\x12\n\nparam_grid\x18\x02 \x01(\t\x12\r\n\x05model\x18\x03 \x01(\x0c\x12\x10\n\x08\x66\x65\x61ture1\x18\x04 \x01(\t\x12\x10\n\x08\x66\x65\x61ture2\x18\x05 \x01(\t\"\x89\x01\n\x14\x45xplanationsResponse\x12\x15\n\rpdp_hp_values\x18\x01 \x01(\t\x12\x12\n\npdp_values\x18\x02 \x01(\t\x12\x10\n\x08pdp2d_xi\x18\x03 \x01(\t\x12\x10\n\x08pdp2d_yi\x18\x04 \x01(\t\x12\x10\n\x08pdp2d_zi\x18\x05 \x01(\t\x12\x10\n\x08\x61le_data\x18\x06 \x01(\t\"\xcd\x01\n\x10InfluenceRequest\x12\x12\n\ntrain_data\x18\x01 \x01(\x0c\x12\r\n\x05model\x18\x02 \x01(\x0c\x12\x11\n\ttest_data\x18\x03 \x01(\x0c\x12\x14\n\x0ctrain_labels\x18\x04 \x01(\x0c\x12\x13\n\x0btest_labels\x18\x05 \x01(\x0c\x12\x17\n\x0fnum_influential\x18\x06 \x01(\x05\x12\x1b\n\x13untransformed_train\x18\x07 \x01(\x0c\x12\"\n\x1auntransformed_train_labels\x18\x08 \x01(\x0c\"K\n\x11InfluenceResponse\x12\x12\n\ninfluences\x18\x01 \x03(\x02\x12\x10\n\x08positive\x18\x02 \x01(\x0c\x12\x10\n\x08negative\x18\x03 \x01(\x0c\x32M\n\x0c\x45xplanations\x12=\n\x0eGetExplanation\x12\x14.ExplanationsRequest\x1a\x15.ExplanationsResponse2J\n\nInfluences\x12<\n\x11\x43omputeInfluences\x12\x11.InfluenceRequest\x1a\x12.InfluenceResponse(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'xai_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_EXPLANATIONSREQUEST']._serialized_start=21
  _globals['_EXPLANATIONSREQUEST']._serialized_end=139
  _globals['_EXPLANATIONSRESPONSE']._serialized_start=142
  _globals['_EXPLANATIONSRESPONSE']._serialized_end=279
  _globals['_INFLUENCEREQUEST']._serialized_start=282
  _globals['_INFLUENCEREQUEST']._serialized_end=487
  _globals['_INFLUENCERESPONSE']._serialized_start=489
  _globals['_INFLUENCERESPONSE']._serialized_end=564
  _globals['_EXPLANATIONS']._serialized_start=566
  _globals['_EXPLANATIONS']._serialized_end=643
  _globals['_INFLUENCES']._serialized_start=645
  _globals['_INFLUENCES']._serialized_end=719
# @@protoc_insertion_point(module_scope)
